services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - bloom-cart-test-data:/var/lib/postgresql/data

volumes:
  bloom-cart-test-data:
